### ISSUE TITLE
zip_choropleth does not exist

### ISSUE THREAD

**Issue by lendle** [arilamstein/choroplethr#3]
The deprecation warning for `zip_map` suggests using `zip_choropleth`, but the function does not exist.

**Comment by dracodoc** [comment]
It's in a separate package. [See this](https://rstudio-pubs-static.s3.amazonaws.com/73396_8172d0d6affb407b9c3ee34fff60f89c.html)

**Comment by arilamstein** [comment]
@lendle ,

Yes, @dracodoc  is correct. When I submitted the package to CRAN they asked me to move `zip_choropleth` into a separate package because the size of the zip code map was so large. That new package is `choroplethrZip`, which you can see here: https://github.com/arilamstein/choroplethrZip.

I just checked and it looks like the warning that `zip_map` issues doesn't point you to the new package. I should update that.
