### ISSUE TITLE
Consider using a better projection for USA maps

### ISSUE THREAD

**Issue by PKI-Kent** [arilamstein/choroplethr#7]
IIUC choroplethr uses coord_quickmap for coordinate projections; it in turn is an approximation to the Mercator projection. This is not a good choice for mapping the entire US; it distorts both the northern US and Alaska. An Albers projection is the conventional projection, see https://source.opennews.org/en-US/learning/choosing-right-map-projection/ for explanation and justification.

Bob Rudis has a nice post showing how to use Albers projection including moving Alaska and Hawaii to inset maps: https://rud.is/b/2014/11/16/moving-the-earth-well-alaska-hawaii-with-r/

**Comment by keberwein** [comment]
+1 for the Alberts equal area, looks much better!

```
us_aea <- spTransform(us, CRS("+proj=laea +lat_0=45 +lon_0=-100 +x_0=0 +y_0=0 +a=6370997 +b=6370997 +units=m +no_defs"))
us_aea@data$id <- rownames(us_aea@data)
```

**Comment by PKI-Kent** [comment]
See also https://github.com/hrbrmstr/albersusa.

**Comment by arilamstein** [comment]
Projections have come up a lot in the context of choroplethr. Here's what I've said about it in the past:

"Administrative Maps and Projections in R": http://www.arilamstein.com/blog/2015/07/23/administrative-level-1-maps-and-projections/

Also, in version v3.2.0 of choroplethr I introduced the `projection` member variable:
http://www.arilamstein.com/blog/2015/08/27/choroplethr-3-2-0-is-now-out/

Choroplethr uses ggplot2. It was intended as a very thin layer around ggplot2 that makes it easy to do a single thing: make choropleth maps from arbitrary shapefiles. 

ggplot2 in turn, I think, does not seems to have a well-defined way to make maps with insets. Or at least, when I was inquiring about how to add the functionality to choroplethr, I didn't get pointed to any kind of authoritative resource. And I remember looking into this quite a bit at the time. But of course, that doesn't mean that I didn't miss something.

I wound up going with custom_annotation, which is what you can see here:

https://github.com/arilamstein/choroplethr/blob/master/R/usa.R#L51

There are a few advantages and disadvantages of this. Regarding this particular discussion of projections, there is one clear disadvantage: custom_annotation only allows square annotations. So you can only add projections to the insets that don't make them rectangles. Or something like that. Or maybe it was that the continental US was limited in the projections it could take. But it was something like that. And this limitation might have been lifted in the intervening years since I wrote this code. I don't read the ggplot2 change logs very closely. 

If you want to make a PR that changes the projection of the US map with insets, then I might accept it. But you would have to be careful that it didn't introduce any problems. Choroplethr is widely used, and has been stable for a very long time. My attention has moved on to other projects, so if I make a change, I need to be sure that it doesn't lead to bug reports.
